// Generated by CIRCT 346a108ea
module Behavior_colorFromSwitches(	// /tmp/output.opt.mlir:2:3
  input        sw0,	// /tmp/output.opt.mlir:2:44
               sw1,	// /tmp/output.opt.mlir:2:58
               sw2,	// /tmp/output.opt.mlir:2:72
  output [7:0] result	// /tmp/output.opt.mlir:2:87
);

  wire _GEN = ~sw1;	// /tmp/output.opt.mlir:11:10
  wire _GEN_0 = ~sw2;	// /tmp/output.opt.mlir:12:10
  wire _GEN_1 = ~sw0;	// /tmp/output.opt.mlir:14:10
  assign result =
    sw0 | sw1 | sw2
      ? (sw0 & _GEN & _GEN_0
           ? 8'h1
           : _GEN_1 & sw1 & _GEN_0
               ? 8'h2
               : _GEN_1 & _GEN & sw2
                   ? 8'h4
                   : sw0 & sw1 & _GEN_0
                       ? 8'h3
                       : _GEN_1 & sw1 & sw2 ? 8'h6 : {6'h1, ~(sw0 & _GEN & sw2), 1'h1})
      : 8'h0;	// /tmp/output.opt.mlir:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:13, :11:10, :12:10, :13:10, :14:10, :15:10, :16:10, :17:10, :18:10, :19:10, :20:10, :21:11, :22:11, :23:11, :24:11, :25:11, :26:11, :27:11, :28:11, :29:5
endmodule

module Behavior_periodFromButtons(	// /tmp/output.opt.mlir:31:3
  input         btn0,	// /tmp/output.opt.mlir:31:44
                btn1,	// /tmp/output.opt.mlir:31:59
                btn2,	// /tmp/output.opt.mlir:31:74
                btn3,	// /tmp/output.opt.mlir:31:89
  input  [12:0] currentPeriodMs,	// /tmp/output.opt.mlir:31:104
  output [12:0] result	// /tmp/output.opt.mlir:31:132
);

  assign result =
    btn3 ? 13'h1F4 : btn2 ? 13'h3E8 : btn1 ? 13'h7D0 : btn0 ? 13'hFA0 : currentPeriodMs;	// /tmp/output.opt.mlir:32:17, :33:18, :34:18, :35:18, :36:10, :37:10, :38:10, :39:10, :40:5
endmodule

module Behavior_ticksPerStep(	// /tmp/output.opt.mlir:42:3
  input  [12:0] periodMs,	// /tmp/output.opt.mlir:42:39
  output [19:0] result	// /tmp/output.opt.mlir:42:60
);

  wire [29:0] _GEN =
    $unsigned($signed($signed({{17{periodMs[12]}}, periodMs} * 30'h186A0) / 30'sh400));	// /tmp/output.opt.mlir:43:18, :44:20, :45:10, :46:10, :47:10, :48:10, :49:10
  assign result = _GEN[19:0];	// /tmp/output.opt.mlir:49:10, :50:10, :51:5
endmodule

module Prelude_colorToRgbBits(	// /tmp/output.opt.mlir:53:3
  input  [7:0]                                                   color,	// /tmp/output.opt.mlir:53:40
  input                                                          bright,	// /tmp/output.opt.mlir:53:56
  output struct packed {logic Item1; logic Item2; logic Item3; } result	// /tmp/output.opt.mlir:53:74
);

  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN =
    '{Item1: 1'h1, Item2: 1'h1, Item3: 1'h1};	// /tmp/output.opt.mlir:54:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_0 =
    '{Item1: 1'h1, Item2: 1'h0, Item3: 1'h1};	// /tmp/output.opt.mlir:55:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_1 =
    '{Item1: 1'h0, Item2: 1'h1, Item3: 1'h1};	// /tmp/output.opt.mlir:56:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_2 =
    '{Item1: 1'h1, Item2: 1'h1, Item3: 1'h0};	// /tmp/output.opt.mlir:57:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_3 =
    '{Item1: 1'h0, Item2: 1'h0, Item3: 1'h1};	// /tmp/output.opt.mlir:58:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_4 =
    '{Item1: 1'h0, Item2: 1'h1, Item3: 1'h0};	// /tmp/output.opt.mlir:59:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_5 =
    '{Item1: 1'h1, Item2: 1'h0, Item3: 1'h0};	// /tmp/output.opt.mlir:60:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_6 =
    '{Item1: 1'h0, Item2: 1'h0, Item3: 1'h0};	// /tmp/output.opt.mlir:61:10
  assign result =
    ~bright | color == 8'h0
      ? _GEN_6
      : color == 8'h1
          ? _GEN_5
          : color == 8'h2
              ? _GEN_4
              : color == 8'h4
                  ? _GEN_3
                  : color == 8'h3
                      ? _GEN_2
                      : color == 8'h6 ? _GEN_1 : color == 8'h5 ? _GEN_0 : _GEN;	// /tmp/output.opt.mlir:54:10, :55:10, :56:10, :57:10, :58:10, :59:10, :60:10, :61:10, :62:14, :63:14, :64:14, :65:14, :66:14, :67:14, :68:14, :70:10, :71:10, :72:11, :73:11, :74:11, :75:11, :76:11, :77:11, :78:11, :79:11, :80:11, :81:11, :82:11, :83:11, :84:11, :85:11, :86:5
endmodule

module Behavior_step(	// /tmp/output.opt.mlir:88:3
  input  struct packed {logic [30:0] Counter; logic [19:0] StepTick; logic [10:0] Phase; logic [12:0] PeriodMs; }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               state,	// /tmp/output.opt.mlir:88:31
  input  struct packed {logic Sw0; logic Sw1; logic Sw2; logic Sw3; logic Btn0; logic Btn1; logic Btn2; logic Btn3; }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           inputs,	// /tmp/output.opt.mlir:88:111
  output struct packed {struct packed {logic [30:0] Counter; logic [19:0] StepTick; logic [10:0] Phase; logic [12:0] PeriodMs; } Item1; struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic PeriodMs; } value; } UartReport; } Item2; } result	// /tmp/output.opt.mlir:88:213
);

  wire struct packed {logic Item1; logic Item2; logic Item3; }
    _Prelude_colorToRgbBits_inst_result;	// /tmp/output.opt.mlir:317:45
  wire struct packed {logic Item1; logic Item2; logic Item3; }
    _Prelude_colorToRgbBits_inst_result_0;	// /tmp/output.opt.mlir:316:45
  wire struct packed {logic Item1; logic Item2; logic Item3; }
    _Prelude_colorToRgbBits_inst_result_1;	// /tmp/output.opt.mlir:315:45
  wire struct packed {logic Item1; logic Item2; logic Item3; }
    _Prelude_colorToRgbBits_inst_result_2;	// /tmp/output.opt.mlir:314:43
  wire [19:0] _Behavior_ticksPerStep_inst_result;	// /tmp/output.opt.mlir:122:42
  wire [12:0] _Behavior_periodFromButtons_inst_result;	// /tmp/output.opt.mlir:118:47
  wire [7:0]  _Behavior_colorFromSwitches_inst_result;	// /tmp/output.opt.mlir:112:47
  wire
    struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic PeriodMs; } value; }
    _GEN = '{tag: 1'h0, value: '{Color: 8'h0, Mode: 1'h0, PeriodMs: 1'h0}};	// /tmp/output.opt.mlir:99:10
  Behavior_colorFromSwitches Behavior_colorFromSwitches_inst (	// /tmp/output.opt.mlir:112:47
    .sw0    (inputs.Sw0),	// /tmp/output.opt.mlir:109:12
    .sw1    (inputs.Sw1),	// /tmp/output.opt.mlir:110:12
    .sw2    (inputs.Sw2),	// /tmp/output.opt.mlir:111:12
    .result (_Behavior_colorFromSwitches_inst_result)
  );	// /tmp/output.opt.mlir:112:47
  Behavior_periodFromButtons Behavior_periodFromButtons_inst (	// /tmp/output.opt.mlir:118:47
    .btn0            (inputs.Btn0),	// /tmp/output.opt.mlir:113:13
    .btn1            (inputs.Btn1),	// /tmp/output.opt.mlir:114:13
    .btn2            (inputs.Btn2),	// /tmp/output.opt.mlir:115:13
    .btn3            (inputs.Btn3),	// /tmp/output.opt.mlir:116:13
    .currentPeriodMs (state.PeriodMs),	// /tmp/output.opt.mlir:117:17
    .result          (_Behavior_periodFromButtons_inst_result)
  );	// /tmp/output.opt.mlir:118:47
  wire [19:0] _GEN_0 = state.StepTick + 20'h1;	// /tmp/output.opt.mlir:108:15, :120:17, :121:10
  Behavior_ticksPerStep Behavior_ticksPerStep_inst (	// /tmp/output.opt.mlir:122:42
    .periodMs (_Behavior_periodFromButtons_inst_result),	// /tmp/output.opt.mlir:118:47
    .result   (_Behavior_ticksPerStep_inst_result)
  );	// /tmp/output.opt.mlir:122:42
  wire        _GEN_1 = $signed(_GEN_0) >= $signed(_Behavior_ticksPerStep_inst_result);	// /tmp/output.opt.mlir:121:10, :122:42, :123:10
  wire [11:0] _GEN_2 =
    $unsigned($signed($signed({state.Phase[10], state.Phase} + 12'h1) % 12'sh400));	// /tmp/output.opt.mlir:98:18, :106:15, :125:14, :126:10, :127:10, :128:10, :129:10
  wire [10:0] _GEN_3 = ~_GEN_1 ? state.Phase : _GEN_2[10:0];	// /tmp/output.opt.mlir:123:10, :124:10, :125:14, :129:10, :130:10, :131:10
  wire [30:0] _GEN_4 = $unsigned($signed($signed(state.Counter + 31'h1) % 31'sh2FAF0800));	// /tmp/output.opt.mlir:97:23, :103:15, :133:16, :134:11, :135:11
  wire [30:0] _GEN_5 = $unsigned($signed($signed(_GEN_4) % 31'sh100));	// /tmp/output.opt.mlir:102:17, :135:11, :136:11
  wire [11:0] _GEN_6 = {_GEN_3[10], _GEN_3};	// /tmp/output.opt.mlir:131:10, :138:11, :139:11
  wire [11:0] _GEN_7 = $unsigned($signed($signed(_GEN_6) % 12'sh400));	// /tmp/output.opt.mlir:98:18, :139:11, :140:11
  wire [9:0]  _GEN_8 = $signed(_GEN_7[10:0]) < 11'sh200 ? 10'h1FF - _GEN_7[9:0] : 10'h0;	// /tmp/output.opt.mlir:94:17, :96:17, :101:15, :140:11, :141:11, :143:11, :144:11, :145:11, :146:11
  wire [10:0] _GEN_9 =
    $signed(_GEN_7[10:0]) < 11'sh100 ? _GEN_7[10:0] : {_GEN_8[9], _GEN_8};	// /tmp/output.opt.mlir:95:17, :140:11, :141:11, :142:11, :146:11, :147:11, :148:11, :149:11
  wire [12:0] _GEN_10 = {{2{_GEN_9[10]}}, _GEN_9} * 13'h3;	// /tmp/output.opt.mlir:100:15, :149:11, :150:11, :151:11, :152:11, :153:11
  wire [23:0] _GEN_11 = {{11{_GEN_10[12]}}, _GEN_10} * {{13{_GEN_9[10]}}, _GEN_9};	// /tmp/output.opt.mlir:149:11, :150:11, :153:11, :154:11, :155:11, :156:11, :157:11, :158:11, :159:11
  wire [21:0] _GEN_12 = {{10{_GEN_9[10]}}, _GEN_9, 1'h0} * {{11{_GEN_9[10]}}, _GEN_9};	// /tmp/output.opt.mlir:93:14, :149:11, :150:11, :160:11, :161:11, :162:11, :163:11, :164:11
  wire [31:0] _GEN_13 =
    $unsigned($signed($signed({{10{_GEN_12[21]}}, _GEN_12} * {{21{_GEN_9[10]}}, _GEN_9})
                      / 32'sh100));	// /tmp/output.opt.mlir:92:17, :149:11, :150:11, :164:11, :165:11, :166:11, :167:11, :168:11, :169:11, :170:11, :171:11
  wire [24:0] _GEN_14 =
    $unsigned($signed($signed({_GEN_11[23], _GEN_11} - {_GEN_13[23], _GEN_13[23:0]})
                      / 25'sh100));	// /tmp/output.opt.mlir:91:17, :159:11, :171:11, :172:11, :173:11, :174:11, :175:11, :176:11, :177:11, :178:11
  wire [16:0] _GEN_15 = {{8{_GEN_5[8]}}, _GEN_5[8:0]};	// /tmp/output.opt.mlir:136:11, :137:11, :180:11, :181:11, :182:11
  wire        _GEN_16 = inputs.Sw3 & $signed(_GEN_15) < $signed(_GEN_14[16:0]);	// /tmp/output.opt.mlir:119:12, :178:11, :179:11, :182:11, :183:11, :184:11
  wire [11:0] _GEN_17 = $unsigned($signed($signed(_GEN_6 + 12'h100) % 12'sh400));	// /tmp/output.opt.mlir:98:18, :105:17, :139:11, :185:11, :186:11
  wire [9:0]  _GEN_18 =
    $signed(_GEN_17[10:0]) < 11'sh200 ? 10'h1FF - _GEN_17[9:0] : 10'h0;	// /tmp/output.opt.mlir:94:17, :96:17, :101:15, :186:11, :187:11, :189:11, :190:11, :191:11, :192:11
  wire [10:0] _GEN_19 =
    $signed(_GEN_17[10:0]) < 11'sh100 ? _GEN_17[10:0] : {_GEN_18[9], _GEN_18};	// /tmp/output.opt.mlir:95:17, :186:11, :187:11, :188:11, :192:11, :193:11, :194:11, :195:11
  wire [12:0] _GEN_20 = {{2{_GEN_19[10]}}, _GEN_19} * 13'h3;	// /tmp/output.opt.mlir:100:15, :195:11, :196:11, :197:11, :198:11, :199:11
  wire [23:0] _GEN_21 = {{11{_GEN_20[12]}}, _GEN_20} * {{13{_GEN_19[10]}}, _GEN_19};	// /tmp/output.opt.mlir:195:11, :196:11, :199:11, :200:11, :201:11, :202:11, :203:11, :204:11, :205:11
  wire [21:0] _GEN_22 = {{10{_GEN_19[10]}}, _GEN_19, 1'h0} * {{11{_GEN_19[10]}}, _GEN_19};	// /tmp/output.opt.mlir:93:14, :195:11, :196:11, :206:11, :207:11, :208:11, :209:11, :210:11
  wire [31:0] _GEN_23 =
    $unsigned($signed($signed({{10{_GEN_22[21]}}, _GEN_22} * {{21{_GEN_19[10]}}, _GEN_19})
                      / 32'sh100));	// /tmp/output.opt.mlir:92:17, :195:11, :196:11, :210:11, :211:11, :212:11, :213:11, :214:11, :215:11, :216:11, :217:11
  wire [24:0] _GEN_24 =
    $unsigned($signed($signed({_GEN_21[23], _GEN_21} - {_GEN_23[23], _GEN_23[23:0]})
                      / 25'sh100));	// /tmp/output.opt.mlir:91:17, :205:11, :217:11, :218:11, :219:11, :220:11, :221:11, :222:11, :223:12, :224:12
  wire        _GEN_25 = inputs.Sw3 & $signed(_GEN_15) < $signed(_GEN_24[16:0]);	// /tmp/output.opt.mlir:119:12, :182:11, :224:12, :225:12, :226:12, :227:12
  wire [11:0] _GEN_26 = $unsigned($signed($signed(_GEN_6 + 12'h200) % 12'sh400));	// /tmp/output.opt.mlir:90:17, :98:18, :139:11, :228:12, :229:12
  wire [9:0]  _GEN_27 =
    $signed(_GEN_26[10:0]) < 11'sh200 ? 10'h1FF - _GEN_26[9:0] : 10'h0;	// /tmp/output.opt.mlir:94:17, :96:17, :101:15, :229:12, :230:12, :232:12, :233:12, :234:12, :235:12
  wire [10:0] _GEN_28 =
    $signed(_GEN_26[10:0]) < 11'sh100 ? _GEN_26[10:0] : {_GEN_27[9], _GEN_27};	// /tmp/output.opt.mlir:95:17, :229:12, :230:12, :231:12, :235:12, :236:12, :237:12, :238:12
  wire [12:0] _GEN_29 = {{2{_GEN_28[10]}}, _GEN_28} * 13'h3;	// /tmp/output.opt.mlir:100:15, :238:12, :239:12, :240:12, :241:12, :242:12
  wire [23:0] _GEN_30 = {{11{_GEN_29[12]}}, _GEN_29} * {{13{_GEN_28[10]}}, _GEN_28};	// /tmp/output.opt.mlir:238:12, :239:12, :242:12, :243:12, :244:12, :245:12, :246:12, :247:12, :248:12
  wire [21:0] _GEN_31 = {{10{_GEN_28[10]}}, _GEN_28, 1'h0} * {{11{_GEN_28[10]}}, _GEN_28};	// /tmp/output.opt.mlir:93:14, :238:12, :239:12, :249:12, :250:12, :251:12, :252:12, :253:12
  wire [31:0] _GEN_32 =
    $unsigned($signed($signed({{10{_GEN_31[21]}}, _GEN_31} * {{21{_GEN_28[10]}}, _GEN_28})
                      / 32'sh100));	// /tmp/output.opt.mlir:92:17, :238:12, :239:12, :253:12, :254:12, :255:12, :256:12, :257:12, :258:12, :259:12, :260:12
  wire [24:0] _GEN_33 =
    $unsigned($signed($signed({_GEN_30[23], _GEN_30} - {_GEN_32[23], _GEN_32[23:0]})
                      / 25'sh100));	// /tmp/output.opt.mlir:91:17, :248:12, :260:12, :261:12, :262:12, :263:12, :264:12, :265:12, :266:12, :267:12
  wire        _GEN_34 = inputs.Sw3 & $signed(_GEN_15) < $signed(_GEN_33[16:0]);	// /tmp/output.opt.mlir:119:12, :182:11, :267:12, :268:12, :269:12, :270:12
  wire [11:0] _GEN_35 = $unsigned($signed($signed(_GEN_6 + 12'h300) % 12'sh400));	// /tmp/output.opt.mlir:89:17, :98:18, :139:11, :271:12, :272:12
  wire [9:0]  _GEN_36 =
    $signed(_GEN_35[10:0]) < 11'sh200 ? 10'h1FF - _GEN_35[9:0] : 10'h0;	// /tmp/output.opt.mlir:94:17, :96:17, :101:15, :272:12, :273:12, :275:12, :276:12, :277:12, :278:12
  wire [10:0] _GEN_37 =
    $signed(_GEN_35[10:0]) < 11'sh100 ? _GEN_35[10:0] : {_GEN_36[9], _GEN_36};	// /tmp/output.opt.mlir:95:17, :272:12, :273:12, :274:12, :278:12, :279:12, :280:12, :281:12
  wire [12:0] _GEN_38 = {{2{_GEN_37[10]}}, _GEN_37} * 13'h3;	// /tmp/output.opt.mlir:100:15, :281:12, :282:12, :283:12, :284:12, :285:12
  wire [23:0] _GEN_39 = {{11{_GEN_38[12]}}, _GEN_38} * {{13{_GEN_37[10]}}, _GEN_37};	// /tmp/output.opt.mlir:281:12, :282:12, :285:12, :286:12, :287:12, :288:12, :289:12, :290:12, :291:12
  wire [21:0] _GEN_40 = {{10{_GEN_37[10]}}, _GEN_37, 1'h0} * {{11{_GEN_37[10]}}, _GEN_37};	// /tmp/output.opt.mlir:93:14, :281:12, :282:12, :292:12, :293:12, :294:12, :295:12, :296:12
  wire [31:0] _GEN_41 =
    $unsigned($signed($signed({{10{_GEN_40[21]}}, _GEN_40} * {{21{_GEN_37[10]}}, _GEN_37})
                      / 32'sh100));	// /tmp/output.opt.mlir:92:17, :281:12, :282:12, :296:12, :297:12, :298:12, :299:12, :300:12, :301:12, :302:12, :303:12
  wire [24:0] _GEN_42 =
    $unsigned($signed($signed({_GEN_39[23], _GEN_39} - {_GEN_41[23], _GEN_41[23:0]})
                      / 25'sh100));	// /tmp/output.opt.mlir:91:17, :291:12, :303:12, :304:12, :305:12, :306:12, :307:12, :308:12, :309:12, :310:12
  wire        _GEN_43 = inputs.Sw3 & $signed(_GEN_15) < $signed(_GEN_42[16:0]);	// /tmp/output.opt.mlir:119:12, :182:11, :310:12, :311:12, :312:12, :313:12
  Prelude_colorToRgbBits Prelude_colorToRgbBits_inst (	// /tmp/output.opt.mlir:314:43
    .color  (_Behavior_colorFromSwitches_inst_result),	// /tmp/output.opt.mlir:112:47
    .bright (_GEN_16),	// /tmp/output.opt.mlir:184:11
    .result (_Prelude_colorToRgbBits_inst_result_2)
  );	// /tmp/output.opt.mlir:314:43
  Prelude_colorToRgbBits Prelude_colorToRgbBits_inst_0 (	// /tmp/output.opt.mlir:315:45
    .color  (_Behavior_colorFromSwitches_inst_result),	// /tmp/output.opt.mlir:112:47
    .bright (_GEN_25),	// /tmp/output.opt.mlir:227:12
    .result (_Prelude_colorToRgbBits_inst_result_1)
  );	// /tmp/output.opt.mlir:315:45
  Prelude_colorToRgbBits Prelude_colorToRgbBits_inst_1 (	// /tmp/output.opt.mlir:316:45
    .color  (_Behavior_colorFromSwitches_inst_result),	// /tmp/output.opt.mlir:112:47
    .bright (_GEN_34),	// /tmp/output.opt.mlir:270:12
    .result (_Prelude_colorToRgbBits_inst_result_0)
  );	// /tmp/output.opt.mlir:316:45
  Prelude_colorToRgbBits Prelude_colorToRgbBits_inst_2 (	// /tmp/output.opt.mlir:317:45
    .color  (_Behavior_colorFromSwitches_inst_result),	// /tmp/output.opt.mlir:112:47
    .bright (_GEN_43),	// /tmp/output.opt.mlir:313:12
    .result (_Prelude_colorToRgbBits_inst_result)
  );	// /tmp/output.opt.mlir:317:45
  wire
    struct packed {logic [30:0] Counter; logic [19:0] StepTick; logic [10:0] Phase; logic [12:0] PeriodMs; }
    _GEN_44 =
    '{Counter: _GEN_4,
      StepTick: (_GEN_1 ? 20'h0 : _GEN_0),
      Phase: _GEN_3,
      PeriodMs: _Behavior_periodFromButtons_inst_result};	// /tmp/output.opt.mlir:104:15, :118:47, :121:10, :123:10, :131:10, :132:11, :135:11, :318:12
  wire
    struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; }
    _GEN_45 =
    '{Led0: _GEN_16,
      Led1: _GEN_25,
      Led2: _GEN_34,
      Led3: _GEN_43,
      Rgb0: _Prelude_colorToRgbBits_inst_result_2,
      Rgb1: _Prelude_colorToRgbBits_inst_result_1,
      Rgb2: _Prelude_colorToRgbBits_inst_result_0,
      Rgb3: _Prelude_colorToRgbBits_inst_result};	// /tmp/output.opt.mlir:184:11, :227:12, :270:12, :313:12, :314:43, :315:45, :316:45, :317:45, :319:12
  wire
    struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic PeriodMs; } value; } UartReport; }
    _GEN_46 = '{Leds: _GEN_45, UartReport: _GEN};	// /tmp/output.opt.mlir:99:10, :319:12, :320:12
  assign result = '{Item1: _GEN_44, Item2: _GEN_46};	// /tmp/output.opt.mlir:318:12, :320:12, :321:12, :322:5
endmodule

module Program_helloArtyTop(	// /tmp/output.opt.mlir:324:3
  input  sys_clk,	// /tmp/output.opt.mlir:324:38
         sw_0,	// /tmp/output.opt.mlir:324:64
         sw_1,	// /tmp/output.opt.mlir:324:79
         sw_2,	// /tmp/output.opt.mlir:324:94
         sw_3,	// /tmp/output.opt.mlir:324:109
         btn_0,	// /tmp/output.opt.mlir:324:124
         btn_1,	// /tmp/output.opt.mlir:324:140
         btn_2,	// /tmp/output.opt.mlir:324:156
         btn_3,	// /tmp/output.opt.mlir:324:172
  output led_0,	// /tmp/output.opt.mlir:324:189
         led_1,	// /tmp/output.opt.mlir:324:205
         led_2,	// /tmp/output.opt.mlir:324:221
         led_3,	// /tmp/output.opt.mlir:324:237
         led0_r,	// /tmp/output.opt.mlir:324:253
         led0_g,	// /tmp/output.opt.mlir:324:270
         led0_b,	// /tmp/output.opt.mlir:324:287
         led1_r,	// /tmp/output.opt.mlir:324:304
         led1_g,	// /tmp/output.opt.mlir:324:321
         led1_b,	// /tmp/output.opt.mlir:324:338
         led2_r,	// /tmp/output.opt.mlir:324:355
         led2_g,	// /tmp/output.opt.mlir:324:372
         led2_b,	// /tmp/output.opt.mlir:324:389
         led3_r,	// /tmp/output.opt.mlir:324:406
         led3_g,	// /tmp/output.opt.mlir:324:423
         led3_b	// /tmp/output.opt.mlir:324:440
);

  wire [12:0] _GEN;	// /tmp/output.opt.mlir:365:17
  wire [10:0] _GEN_0;	// /tmp/output.opt.mlir:364:14
  wire [19:0] _GEN_1;	// /tmp/output.opt.mlir:363:17
  wire [30:0] _GEN_2;	// /tmp/output.opt.mlir:362:16
  wire
    struct packed {struct packed {logic [30:0] Counter; logic [19:0] StepTick; logic [10:0] Phase; logic [12:0] PeriodMs; } Item1; struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic PeriodMs; } value; } UartReport; } Item2; }
    _step_inst_result;	// /tmp/output.opt.mlir:338:25
  reg         v1;	// /tmp/output.opt.mlir:330:11
  always_ff @(posedge sys_clk)	// /tmp/output.opt.mlir:330:11
    v1 <= 1'h1;	// /tmp/output.opt.mlir:329:13, :330:11
  wire        _GEN_3 = ~v1;	// /tmp/output.opt.mlir:330:11, :331:10
  reg  [30:0] v7;	// /tmp/output.opt.mlir:332:11
  always_ff @(posedge sys_clk) begin	// /tmp/output.opt.mlir:332:11
    if (_GEN_3)	// /tmp/output.opt.mlir:331:10, :332:11
      v7 <= 31'h0;	// /tmp/output.opt.mlir:328:15, :332:11
    else	// /tmp/output.opt.mlir:331:10, :332:11
      v7 <= _GEN_2;	// /tmp/output.opt.mlir:332:11, :362:16
  end // always_ff @(posedge)
  reg  [19:0] v8;	// /tmp/output.opt.mlir:333:11
  always_ff @(posedge sys_clk) begin	// /tmp/output.opt.mlir:333:11
    if (_GEN_3)	// /tmp/output.opt.mlir:331:10, :333:11
      v8 <= 20'h0;	// /tmp/output.opt.mlir:327:15, :333:11
    else	// /tmp/output.opt.mlir:331:10, :333:11
      v8 <= _GEN_1;	// /tmp/output.opt.mlir:333:11, :363:17
  end // always_ff @(posedge)
  reg  [10:0] v9;	// /tmp/output.opt.mlir:334:11
  always_ff @(posedge sys_clk) begin	// /tmp/output.opt.mlir:334:11
    if (_GEN_3)	// /tmp/output.opt.mlir:331:10, :334:11
      v9 <= 11'h0;	// /tmp/output.opt.mlir:326:15, :334:11
    else	// /tmp/output.opt.mlir:331:10, :334:11
      v9 <= _GEN_0;	// /tmp/output.opt.mlir:334:11, :364:14
  end // always_ff @(posedge)
  reg  [12:0] v10;	// /tmp/output.opt.mlir:335:12
  always_ff @(posedge sys_clk) begin	// /tmp/output.opt.mlir:335:12
    if (_GEN_3)	// /tmp/output.opt.mlir:331:10, :335:12
      v10 <= 13'hFA0;	// /tmp/output.opt.mlir:325:18, :335:12
    else	// /tmp/output.opt.mlir:331:10, :335:12
      v10 <= _GEN;	// /tmp/output.opt.mlir:335:12, :365:17
  end // always_ff @(posedge)
  wire
    struct packed {logic Sw0; logic Sw1; logic Sw2; logic Sw3; logic Btn0; logic Btn1; logic Btn2; logic Btn3; }
    _GEN_4 =
    '{Sw0: sw_0,
      Sw1: sw_1,
      Sw2: sw_2,
      Sw3: sw_3,
      Btn0: btn_0,
      Btn1: btn_1,
      Btn2: btn_2,
      Btn3: btn_3};	// /tmp/output.opt.mlir:336:10
  wire
    struct packed {logic [30:0] Counter; logic [19:0] StepTick; logic [10:0] Phase; logic [12:0] PeriodMs; }
    _GEN_5 = '{Counter: v7, StepTick: v8, Phase: v9, PeriodMs: v10};	// /tmp/output.opt.mlir:332:11, :333:11, :334:11, :335:12, :337:10
  Behavior_step step_inst (	// /tmp/output.opt.mlir:338:25
    .state  (_GEN_5),	// /tmp/output.opt.mlir:337:10
    .inputs (_GEN_4),	// /tmp/output.opt.mlir:336:10
    .result (_step_inst_result)
  );	// /tmp/output.opt.mlir:338:25
  assign _GEN_2 = _step_inst_result.Item1.Counter;	// /tmp/output.opt.mlir:338:25, :339:14, :362:16
  assign _GEN_1 = _step_inst_result.Item1.StepTick;	// /tmp/output.opt.mlir:338:25, :339:14, :363:17
  assign _GEN_0 = _step_inst_result.Item1.Phase;	// /tmp/output.opt.mlir:338:25, :339:14, :364:14
  assign _GEN = _step_inst_result.Item1.PeriodMs;	// /tmp/output.opt.mlir:338:25, :339:14, :365:17
  assign led_0 = _step_inst_result.Item2.Leds.Led0;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :342:13, :366:5
  assign led_1 = _step_inst_result.Item2.Leds.Led1;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :343:13, :366:5
  assign led_2 = _step_inst_result.Item2.Leds.Led2;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :344:13, :366:5
  assign led_3 = _step_inst_result.Item2.Leds.Led3;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :345:13, :366:5
  assign led0_r = _step_inst_result.Item2.Leds.Rgb0.Item1;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :346:13, :347:16, :366:5
  assign led0_g = _step_inst_result.Item2.Leds.Rgb0.Item2;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :346:13, :348:16, :366:5
  assign led0_b = _step_inst_result.Item2.Leds.Rgb0.Item3;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :346:13, :349:14, :366:5
  assign led1_r = _step_inst_result.Item2.Leds.Rgb1.Item1;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :350:13, :351:16, :366:5
  assign led1_g = _step_inst_result.Item2.Leds.Rgb1.Item2;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :350:13, :352:16, :366:5
  assign led1_b = _step_inst_result.Item2.Leds.Rgb1.Item3;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :350:13, :353:16, :366:5
  assign led2_r = _step_inst_result.Item2.Leds.Rgb2.Item1;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :354:13, :355:16, :366:5
  assign led2_g = _step_inst_result.Item2.Leds.Rgb2.Item2;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :354:13, :356:16, :366:5
  assign led2_b = _step_inst_result.Item2.Leds.Rgb2.Item3;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :354:13, :357:16, :366:5
  assign led3_r = _step_inst_result.Item2.Leds.Rgb3.Item1;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :358:13, :359:16, :366:5
  assign led3_g = _step_inst_result.Item2.Leds.Rgb3.Item2;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :358:13, :360:16, :366:5
  assign led3_b = _step_inst_result.Item2.Leds.Rgb3.Item3;	// /tmp/output.opt.mlir:338:25, :340:14, :341:13, :358:13, :361:17, :366:5
endmodule

