// Generated by CIRCT 346a108ea
module Behavior_colorFromSwitches(	// output.sv:2:3
  input        sw0,	// output.sv:2:44
               sw1,	// output.sv:2:58
               sw2,	// output.sv:2:72
  output [7:0] result	// output.sv:2:87
);

  wire _GEN = ~sw1;	// output.sv:11:10, :12:10
  wire _GEN_0 = ~sw2;	// output.sv:14:10, :15:10
  wire _GEN_1 = ~sw0;	// output.sv:21:10, :22:10
  assign result =
    sw0 | sw1 | sw2
      ? (sw0 & _GEN & _GEN_0
           ? 8'h1
           : _GEN_1 & sw1 & _GEN_0
               ? 8'h2
               : _GEN_1 & _GEN & sw2
                   ? 8'h4
                   : sw0 & sw1 & _GEN_0
                       ? 8'h3
                       : _GEN_1 & sw1 & sw2 ? 8'h6 : {6'h1, ~(sw0 & _GEN & sw2), 1'h1})
      : 8'h0;	// output.sv:3:14, :4:14, :5:14, :6:14, :7:14, :8:14, :9:14, :10:13, :17:10, :18:10, :19:10, :20:10, :24:11, :25:11, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11, :34:11, :35:11, :36:11, :37:11, :38:11, :39:11, :40:11, :41:11, :42:11, :43:11, :44:11, :45:11, :46:11, :47:11, :48:11, :49:11, :50:11, :51:5
endmodule

module Behavior_modeFromSwitch(	// output.sv:53:3
  input  sw3,	// output.sv:53:41
  output result	// output.sv:53:56
);

  assign result = sw3;	// output.sv:54:5
endmodule

module Behavior_clampPeriod(	// output.sv:56:3
  input  [63:0] value,	// output.sv:56:38
  output [63:0] result	// output.sv:56:56
);

  assign result =
    $signed(value) < 64'sh64 ? 64'h64 : $signed(value) > 64'sh7D0 ? 64'h7D0 : value;	// output.sv:57:18, :58:17, :59:10, :60:10, :61:10, :62:10, :63:5
endmodule

module Behavior_applyCadenceButtons(	// output.sv:65:3
  input  [63:0] periodMs,	// output.sv:65:46
  input         btn0,	// output.sv:65:66
                btn1,	// output.sv:65:81
                btn3,	// output.sv:65:96
  output [63:0] result	// output.sv:65:112
);

  Behavior_clampPeriod Behavior_clampPeriod_inst (	// output.sv:79:41
    .value
      (btn3
         ? 64'h1F4
         : btn0 & ~btn1
             ? periodMs - 64'h64
             : btn1 & ~btn0 ? periodMs + 64'h64 : periodMs),	// output.sv:66:17, :67:17, :69:10, :70:10, :71:19, :72:10, :73:10, :74:10, :75:10, :76:10, :77:10, :78:10
    .result (result)
  );	// output.sv:79:41
endmodule

module Behavior_nextState(	// output.sv:82:3
  input                                                                         sw0,	// output.sv:82:36
                                                                                sw1,	// output.sv:82:50
                                                                                sw2,	// output.sv:82:64
                                                                                sw3,	// output.sv:82:78
                                                                                btn0,	// output.sv:82:92
                                                                                btn1,	// output.sv:82:107
                                                                                btn2,	// output.sv:82:122
                                                                                btn3,	// output.sv:82:137
  input  [63:0]                                                                 currentPeriodMs,	// output.sv:82:152
  output struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; } result	// output.sv:82:180
);

  wire [63:0] _Behavior_applyCadenceButtons_inst_result;	// output.sv:83:50
  wire        _Behavior_modeFromSwitch_inst_result;	// output.sv:84:45
  wire [7:0]  _Behavior_colorFromSwitches_inst_result;	// output.sv:85:48
  Behavior_colorFromSwitches Behavior_colorFromSwitches_inst (	// output.sv:86:47
    .sw0    (sw0),
    .sw1    (sw1),
    .sw2    (sw2),
    .result (_Behavior_colorFromSwitches_inst_result)
  );	// output.sv:86:47
  Behavior_modeFromSwitch Behavior_modeFromSwitch_inst (	// output.sv:88:44
    .sw3    (sw3),
    .result (_Behavior_modeFromSwitch_inst_result)
  );	// output.sv:88:44
  Behavior_applyCadenceButtons Behavior_applyCadenceButtons_inst (	// output.sv:90:49
    .periodMs (currentPeriodMs),
    .btn0     (btn0),
    .btn1     (btn1),
    .btn3     (btn3),
    .result   (_Behavior_applyCadenceButtons_inst_result)
  );	// output.sv:90:49
  assign result =
    '{Color: _Behavior_colorFromSwitches_inst_result,
      Mode: _Behavior_modeFromSwitch_inst_result,
      PeriodMs: _Behavior_applyCadenceButtons_inst_result};	// output.sv:92:10, :93:10, :94:10, :95:10, :96:5
endmodule

module Prelude_isLedOn(	// output.sv:98:3
  input         mode,	// output.sv:98:33
  input  [63:0] counter,	// output.sv:98:48
                periodMs,	// output.sv:98:67
  output        result	// output.sv:98:88
);

  wire [63:0] _GEN = periodMs * 64'h186A0;	// output.sv:101:20, :102:10, :103:10
  assign result =
    ~mode | $signed($signed(counter) % $signed({_GEN[62:0], 1'h0})) < $signed(_GEN);	// output.sv:100:14, :105:10, :106:10, :107:10, :108:10, :109:10, :110:10, :111:10, :112:10, :113:5
endmodule

module Prelude_colorToRgbBits(	// output.sv:115:3
  input  [7:0]                                                   color,	// output.sv:115:40
  input                                                          bright,	// output.sv:115:56
  output struct packed {logic Item1; logic Item2; logic Item3; } result	// output.sv:115:74
);

  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN =
    '{Item1: 1'h1, Item2: 1'h1, Item3: 1'h1};	// output.sv:116:10, :117:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_0 =
    '{Item1: 1'h1, Item2: 1'h0, Item3: 1'h1};	// output.sv:119:10, :120:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_1 =
    '{Item1: 1'h0, Item2: 1'h1, Item3: 1'h1};	// output.sv:122:10, :123:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_2 =
    '{Item1: 1'h1, Item2: 1'h1, Item3: 1'h0};	// output.sv:125:10, :126:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_3 =
    '{Item1: 1'h0, Item2: 1'h0, Item3: 1'h1};	// output.sv:128:10, :129:10
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_4 =
    '{Item1: 1'h0, Item2: 1'h1, Item3: 1'h0};	// output.sv:131:11, :132:11
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_5 =
    '{Item1: 1'h1, Item2: 1'h0, Item3: 1'h0};	// output.sv:134:11, :135:11
  wire struct packed {logic Item1; logic Item2; logic Item3; } _GEN_6 =
    '{Item1: 1'h0, Item2: 1'h0, Item3: 1'h0};	// output.sv:137:11, :138:11
  assign result =
    ~bright | color == 8'h0
      ? _GEN_6
      : color == 8'h1
          ? _GEN_5
          : color == 8'h2
              ? _GEN_4
              : color == 8'h4
                  ? _GEN_3
                  : color == 8'h3
                      ? _GEN_2
                      : color == 8'h6 ? _GEN_1 : color == 8'h5 ? _GEN_0 : _GEN;	// output.sv:140:14, :141:14, :142:14, :143:14, :144:14, :145:14, :146:14, :148:11, :149:11, :150:11, :151:11, :152:11, :153:11, :154:11, :155:11, :156:11, :157:11, :158:11, :159:11, :160:11, :161:11, :162:11, :163:11, :164:11, :165:11, :166:11, :167:11, :168:11, :169:11, :170:11, :171:11, :172:5
endmodule

module Behavior_step(	// output.sv:174:3
  input  struct packed {logic [63:0] Counter; logic [63:0] PeriodMs; }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      state,	// output.sv:174:31
  input  struct packed {logic Sw0; logic Sw1; logic Sw2; logic Sw3; logic Btn0; logic Btn1; logic Btn2; logic Btn3; }                                                                                                                                                                                                                                                                                                                                                                                                                                                       inputs,	// output.sv:174:84
  output struct packed {struct packed {logic [63:0] Counter; logic [63:0] PeriodMs; } Item1; struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; } value; } UartReport; } Item2; } result	// output.sv:174:186
);

  wire struct packed {logic Item1; logic Item2; logic Item3; }
    _Prelude_colorToRgbBits_inst_result;	// output.sv:175:44
  wire        _Prelude_isLedOn_inst_result;	// output.sv:176:37
  wire struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; }
    _Behavior_nextState_inst_result;	// output.sv:177:40
  wire
    struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; } value; }
    _GEN = '{tag: 1'h0, value: '{Color: 8'h0, Mode: 1'h0, PeriodMs: 64'h0}};	// output.sv:179:10, :180:10
  Behavior_nextState Behavior_nextState_inst (	// output.sv:192:39
    .sw0             (inputs.Sw0),	// output.sv:183:12
    .sw1             (inputs.Sw1),	// output.sv:184:12
    .sw2             (inputs.Sw2),	// output.sv:185:12
    .sw3             (inputs.Sw3),	// output.sv:186:12
    .btn0            (inputs.Btn0),	// output.sv:187:13
    .btn1            (inputs.Btn1),	// output.sv:188:13
    .btn2            (inputs.Btn2),	// output.sv:189:13
    .btn3            (inputs.Btn3),	// output.sv:190:13
    .currentPeriodMs (state.PeriodMs),	// output.sv:191:17
    .result          (_Behavior_nextState_inst_result)
  );	// output.sv:192:39
  wire [63:0] _GEN_0 = $unsigned($signed($signed(state.Counter + 64'h1) % 64'sh17D78400));	// output.sv:178:23, :182:15, :194:16, :195:10, :196:10, :197:10
  Prelude_isLedOn Prelude_isLedOn_inst (	// output.sv:204:36
    .mode     (_Behavior_nextState_inst_result.Mode),	// output.sv:199:10, :200:13
    .counter  (_GEN_0),	// output.sv:203:10
    .periodMs (_Behavior_nextState_inst_result.PeriodMs),	// output.sv:201:10, :202:19
    .result   (_Prelude_isLedOn_inst_result)
  );	// output.sv:204:36
  Prelude_colorToRgbBits Prelude_colorToRgbBits_inst (	// output.sv:209:43
    .color  (_Behavior_nextState_inst_result.Color),	// output.sv:206:10, :207:14
    .bright (_Prelude_isLedOn_inst_result),	// output.sv:208:10
    .result (_Prelude_colorToRgbBits_inst_result)
  );	// output.sv:209:43
  wire struct packed {logic [63:0] Counter; logic [63:0] PeriodMs; } _GEN_1 =
    '{Counter: _GEN_0, PeriodMs: _Behavior_nextState_inst_result.PeriodMs};	// output.sv:201:10, :202:19, :211:11, :212:11, :213:11
  wire
    struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; }
    _GEN_2 =
    '{Led0: _Prelude_isLedOn_inst_result,
      Led1: _Prelude_isLedOn_inst_result,
      Led2: _Prelude_isLedOn_inst_result,
      Led3: _Prelude_isLedOn_inst_result,
      Rgb0: _Prelude_colorToRgbBits_inst_result,
      Rgb1: _Prelude_colorToRgbBits_inst_result,
      Rgb2: _Prelude_colorToRgbBits_inst_result,
      Rgb3: _Prelude_colorToRgbBits_inst_result};	// output.sv:215:11, :216:11, :217:11, :218:11, :219:11, :220:11, :221:11, :222:11, :223:11, :224:11
  wire
    struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; } value; } UartReport; }
    _GEN_3 = '{Leds: _GEN_2, UartReport: _GEN};	// output.sv:226:11, :227:11, :228:11, :229:11
  assign result = '{Item1: _GEN_1, Item2: _GEN_3};	// output.sv:231:11, :232:11, :233:11, :234:5
endmodule

module Program_helloArtyTop(	// output.sv:236:3
  input                                                                                                                                                                                                                                                                                                                                                                                                                                                                        clk,	// output.sv:236:38
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               rst,	// output.sv:236:52
  input  struct packed {logic Sw0; logic Sw1; logic Sw2; logic Sw3; logic Btn0; logic Btn1; logic Btn2; logic Btn3; }                                                                                                                                                                                                                                                                                                                                                          inputs,	// output.sv:236:66
  output struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; } value; } UartReport; } outputs	// output.sv:236:168
);

  wire [63:0] _GEN;	// output.sv:237:10
  wire [63:0] _GEN_0;	// output.sv:238:10
  wire
    struct packed {struct packed {logic [63:0] Counter; logic [63:0] PeriodMs; } Item1; struct packed {struct packed {logic Led0; logic Led1; logic Led2; logic Led3; struct packed {logic Item1; logic Item2; logic Item3; } Rgb0; struct packed {logic Item1; logic Item2; logic Item3; } Rgb1; struct packed {logic Item1; logic Item2; logic Item3; } Rgb2; struct packed {logic Item1; logic Item2; logic Item3; } Rgb3; } Leds; struct packed {logic tag; struct packed {logic [7:0] Color; logic Mode; logic [63:0] PeriodMs; } value; } UartReport; } Item2; }
    _step_inst_result;	// output.sv:239:26
  reg  [63:0] v2;	// output.sv:242:11
  always_ff @(posedge clk) begin	// output.sv:243:5
    if (rst)	// output.sv:243:5
      v2 <= 64'h0;	// output.sv:240:15, :247:7
    else	// output.sv:243:5
      v2 <= _GEN_0;	// output.sv:244:12, :245:7
  end // always_ff @(posedge)
  reg  [63:0] v3;	// output.sv:249:11
  always_ff @(posedge clk) begin	// output.sv:250:5
    if (rst)	// output.sv:250:5
      v3 <= 64'h1F4;	// output.sv:241:17, :254:7
    else	// output.sv:250:5
      v3 <= _GEN;	// output.sv:251:12, :252:7
  end // always_ff @(posedge)
  wire struct packed {logic [63:0] Counter; logic [63:0] PeriodMs; } _GEN_1 =
    '{Counter: v2, PeriodMs: v3};	// output.sv:256:10, :257:10, :258:10, :259:10
  Behavior_step step_inst (	// output.sv:262:25
    .state  (_GEN_1),	// output.sv:261:10
    .inputs (inputs),
    .result (_step_inst_result)
  );	// output.sv:262:25
  assign _GEN_0 = _step_inst_result.Item1.Counter;	// output.sv:264:10, :265:14, :268:16, :269:5
  assign _GEN = _step_inst_result.Item1.PeriodMs;	// output.sv:264:10, :265:14, :270:17, :271:5
  assign outputs = _step_inst_result.Item2;	// output.sv:266:10, :267:14, :272:5
endmodule

